export default [
  {
    name: 'The Wonderful And Dynamic Goshogawara',
    min_range: 1,
    max_range: 2,
    speed: 5,
    attack: 4,
    description_1: 'If the opponent initiated, +3 Speed. Hit: Push 1.',
    description_2: '+1 Power and +1 Speed. Now: Draw 1.',
    type: 'ultra',
    gauge: 3,
    total: 2,
  },
  {
    name: 'Totsugekll',
    min_range: 1,
    max_range: 1,
    speed: 5,
    attack: 4,
    description_1: 'Before: Close 3. Hit: Push 2. Gain Advantage.',
    description_2: '+1 Power and +4 Guard.',
    type: 'special',
    total: 2,
  },
  {
    name: 'Overhead Kiss',
    min_range: 1,
    max_range: 1,
    speed: 3,
    attack: 4,
    description_1: 'Ignore Armor. Ignore Guard. Hit: Push 2. Gain Advantage.',
    description_2: 'Now: Draw 2. Hit: Gain Advantage.',
    type: 'special',
    total: 2,
  },
  {
    name: 'Mr. Dolphin',
    min_range: 1,
    max_range: 2,
    speed: 4,
    attack: 4,
    description_1: 'Before: Close 2; if you Closed fewer than 2 spaces, +2 Power.',
    description_2: '+1 Speed. Now: Advance 1.',
    type: 'special',
    total: 2,
  },
  {
    name: 'Great Yamada Attack',
    min_range: 2,
    max_range: 4,
    speed: 1,
    attack: 6,
    description_1: 'Stun Immunity. After: Close 3.',
    description_2: 'Close 3. You may spend 1 Force; if you do, Strike.',
    gauge: 3,
    type: 'ultra',
    total: 2,
  },
  {
    name: 'Anchor Swing',
    min_range: 1,
    max_range: 2,
    speed: 2,
    attack: 5,
    guard: 6,
    description_1: 'Before: Close 1. Hit: Add the top card of your deck to your Gauge.',
    description_2: '+1 Power. Now: Advance or Retreat 2.',
    type: 'special',
    total: 2,
  },
  {
    name: 'Arisugawa Sparkle',
    min_range: 2,
    max_range: 4,
    speed: 4,
    attack: 3,
    armor: 2,
    guard: 3,
    description_1: 'After: Close 1. Draw 1.',
    description_2: 'Discard your hand. Draw 4. Strike.',
    type: 'special',
    total: 2,
  },
] as CardData[]
