export default [
  {
    name: 'Cross',
    min_range: 1,
    max_range: 2,
    speed: 6,
    attack: 3,
    description_1: 'After: Retreat 3.',
    description_2: 'Push or Pull 2; if the opponent was Pulled past you, add this to your Gauge.',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Dive',
    min_range: 1,
    max_range: 1,
    speed: 4,
    attack: 5,
    description_1: 'Before: Advance 3; if you Advanced past the opponent, their attacks do not hit you.',
    description_2: 'Discard a Continuous Boost from play.',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Dust',
    min_range: 2,
    max_range: 3,
    speed: 3,
    attack: 5,
    guard: 4,
    description_1: 'Ignore Armor. Ignore Guard.',
    description_2: '+4 Guard. At the start of your turn, add this to your Gauge.',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Focus',
    min_range: 1,
    max_range: 2,
    speed: 1,
    attack: 4,
    armor: 2,
    guard: 5,
    description_1: 'You cannot be Pushed or Pulled. After: Draw 1.',
    description_2: 'When you initiate a Strike, the opponent must respond with a Wild Swing.',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Grasp',
    min_range: 1,
    max_range: 1,
    speed: 7,
    attack: 3,
    description_1: 'Hit: Push or Pull 1 or 2.',
    description_2: 'Now: Draw 1. Hit: +1 Power. Add this to your Gauge.',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Sweep',
    min_range: 1,
    max_range: 3,
    speed: 2,
    attack: 6,
    guard: 6,
    description_1: 'Hit: The opponent must discard a random card.',
    description_2: 'Your attack is EX (EX Attacks have +1 Power, +1 Speed, +1 Armor, and +1 Guard).',
    type: 'normal',
    total: 2,
  },
  {
    name: 'Block',
    min_range: 'N/A',
    max_range: 'N/A',
    speed: 0,
    armor: 2,
    guard: 3,
    description_1: 'When you are hit (after Hit effects), spend any amount of Force. For each Force spent, +2 Armor. After: Add this to your Gauge at the end of the Strike.',
    description_2: 'Name a card. The opponent must discard a copy of that card or reveal a hand with none.',
    type: 'normal',
    total: 2,
  },
] as CardData[]
